apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2021-06-18T12:51:43Z"
    labels:
      app: a47df425-aa98-4cd7-a6b3-28b3f72b5f05
      openanalytics.eu/sp-instance: 65768f6135998c5ea82268719d10ff5c4d1bdb13
      openanalytics.eu/sp-proxied-app: "true"
      openanalytics.eu/sp-proxy-created-timestamp: "1624020703472"
      openanalytics.eu/sp-proxy-id: 112b62b8-9710-47a2-8003-7a0295e29717
      openanalytics.eu/sp-spec-id: nginx
      openanalytics.eu/sp-user-groups: SCIENTISTS
      openanalytics.eu/sp-user-id: jack
    name: sp-pod-a47df425-aa98-4cd7-a6b3-28b3f72b5f05
    namespace: vlab-jack
    resourceVersion: "63746"
    uid: 3eb328c5-f540-4eb2-87a1-5ca2d547237b
  spec:
    containers:
    - env:
      - name: SHINYPROXY_USERNAME
        value: jack
      - name: SHINYPROXY_USERGROUPS
        value: SCIENTISTS
      - name: SHINYPROXY_PUBLIC_PATH
        value: /app_direct/nginx/
      image: nginx
      imagePullPolicy: Always
      name: sp-container-a47df425-aa98-4cd7-a6b3-28b3f72b5f05
      ports:
      - containerPort: 80
        protocol: TCP
      resources:
        limits:
          cpu: 300m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 100Mi
      securityContext:
        privileged: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nginx-volume
        subPath: nginx
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-s5ng5
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: pvc-jack
    - name: kube-api-access-s5ng5
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-06-18T12:51:43Z"
      message: '0/3 nodes are available: 3 persistentvolumeclaim "pvc-jack" not found.'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: Burstable
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2021-06-18T11:50:21Z"
    labels:
      app: 344f61a5-c0c9-4928-813b-e84c4abc326f
      openanalytics.eu/sp-instance: 20dd8d4f562b63c0777b3fd231ce46de2ec0a0bb
      openanalytics.eu/sp-proxied-app: "true"
      openanalytics.eu/sp-proxy-created-timestamp: "1624017021693"
      openanalytics.eu/sp-proxy-id: 112ba630-f719-41f4-ae84-1771b89372b0
      openanalytics.eu/sp-spec-id: vscode-sidu
      openanalytics.eu/sp-user-groups: SCIENTISTS
      openanalytics.eu/sp-user-id: jack
    name: sp-pod-344f61a5-c0c9-4928-813b-e84c4abc326f
    namespace: vlab-jack
    resourceVersion: "63796"
    uid: dc8aeb93-3422-437d-a83f-fd64078050f2
  spec:
    containers:
    - command:
      - -start.sh
      env:
      - name: SHINYPROXY_USERNAME
        value: jack
      - name: SHINYPROXY_USERGROUPS
        value: SCIENTISTS
      - name: MYSQL_ROOT_PASSWORD
        value: "12345"
      - name: SHINYPROXY_PUBLIC_PATH
        value: /app_direct/vscode-sidu/
      image: cswclui/vscode-sidu:1.0
      imagePullPolicy: IfNotPresent
      name: sp-container-344f61a5-c0c9-4928-813b-e84c4abc326f
      ports:
      - containerPort: 8081
        protocol: TCP
      resources:
        limits:
          cpu: 300m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 100Mi
      securityContext:
        privileged: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xbj9f
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: k3d-worker2-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-xbj9f
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-06-18T11:50:21Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-06-18T11:50:21Z"
      message: 'containers with unready status: [sp-container-344f61a5-c0c9-4928-813b-e84c4abc326f]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-06-18T11:50:21Z"
      message: 'containers with unready status: [sp-container-344f61a5-c0c9-4928-813b-e84c4abc326f]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-06-18T11:50:21Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://b263ed81de18b0c72ab2b00c2545580ea647c93c2a798efc0d30ca626786048e
      image: docker.io/cswclui/vscode-sidu:1.0
      imageID: docker.io/cswclui/vscode-sidu@sha256:d7ad57608327f58e8598aa26a6444aadbc44c0a9b4c9986f54f10094f369f5aa
      lastState:
        terminated:
          containerID: containerd://b263ed81de18b0c72ab2b00c2545580ea647c93c2a798efc0d30ca626786048e
          exitCode: 128
          finishedAt: "2021-06-18T12:52:27Z"
          message: 'failed to create containerd task: OCI runtime create failed: container_linux.go:380:
            starting container process caused: exec: "-start.sh": executable file
            not found in $PATH: unknown'
          reason: StartError
          startedAt: "1970-01-01T00:00:00Z"
      name: sp-container-344f61a5-c0c9-4928-813b-e84c4abc326f
      ready: false
      restartCount: 17
      started: false
      state:
        waiting:
          message: 'failed to create containerd task: OCI runtime create failed: container_linux.go:380:
            starting container process caused: exec: "-start.sh": executable file
            not found in $PATH: unknown'
          reason: RunContainerError
    hostIP: 172.21.0.5
    phase: Running
    podIP: 10.42.2.13
    podIPs:
    - ip: 10.42.2.13
    qosClass: Burstable
    startTime: "2021-06-18T11:50:21Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
