kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-admin
subjects:
  - kind: ServiceAccount
    name: shinyproxy
    apiGroup: ""
    namespace: aiden
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io