apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: vlab-jack
spec:
  volumes:
    - name: docker-volume
      persistentVolumeClaim:
        claimName: docker-pvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/docker"
          name: docker-volume
