{
 "title": "test2",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Memory usage by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"vlab-jack\"}) by (pod) \n   + on(pod) group_left(label_openanalytics_eu_sp_user_id,label_openanalytics_eu_sp_spec_id)\n(\n   0 * kube_pod_labels\n)"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"vlab-jack\"}) by (pod)\n   + on(pod) group_left(label_openanalytics_eu_sp_user_id,label_openanalytics_eu_sp_spec_id)\n(\n   0 * kube_pod_labels\n)"
    }
   ]
  },
  {
   "title": "App Start Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "appStarts_total" }
   ]
  }
 ]
}