additionalScrapeConfigs: 
  - job_name: 'shinyproxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # note: this is the port of ShinyProxy Actuator services, not the port of Prometheus which is by default also 9090
      - targets: ['shinyproxy.shinyproxy.svc.cluster.local:9090'] 