prometheus:
  prometheusSpec:
    additionalScrapeConfigs: 
      - job_name: 'shinyproxy'
        metrics_path: '/actuator/prometheus'
        static_configs:
          # note: this is the port of ShinyProxy Actuator services, not the port of Prometheus which is by default also 9090
          - targets: ['shinyproxy.shinyproxy.svc.cluster.local:9090'] 

kube-state-metrics:
  namespaceOverride: ""
  rbac:
    create: true
  podSecurityPolicy:
    enabled: true
  extraArgs: 
    - "--metric-labels-allowlist=pods=[openanalytics.eu/sp-user-id, openanalytics.eu/sp-spec-id, openanalytics.eu/sp-proxy-created-timestamp,COURSEID]"



    