apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinyproxy-pvc
  namespace: shinyproxy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 200Mi

      