apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinyproxy-pvc
  namespace: shinyproxy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 200Mi