apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod
  namespace: shinyproxy
spec:
  containers:
  - name: init-shinyproxy
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["tail","-f","/dev/null"]
    volumeMounts:
    - name: test
      mountPath: /etc/shinyproxy
    ports:
    - containerPort: 80
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: ceph-pvc