version: '3.6'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - 9100:9100
    volumes:
      - '/:/host'
    networks:
      - mynetwork
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - mynetwork
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - mynetwork
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    security_opt: #supress the mbind: Operation not permitted error message
      - seccomp:unconfined
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - mynetwork
  mysql-exporter:
    image: prom/mysqld-exporter
    restart: always
    ports: 
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: "exporter:12345@(mysql:3306)/"
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true

    