apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10000Mi
